name: Release container images

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  ApplicationName: redis-operator
  QuayImageName: liupeng0518/redis-operator
  AppVersion: "v0.15.1"
  DOCKERFILE_PATH: '**/Dockerfile'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

  build_multi_arch:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Build and push multi-arch latest image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.QuayImageName }}:${{ env.AppVersion }}, ${{ env.QuayImageName }}:latest
